kind: pipeline
name: default
steps:
  - name: deploy
    image: lachlanevenson/k8s-kubectl
    environment:
      KUBE_CONFIG:
        from_secret: kube_config
    commands:
      - mkdir -p ~/.kube
      - echo "$KUBE_CONFIG" > ~/.kube/config
      - pwd
      - ls
      - ls bin/deploy-cluster.sh
      # - ./bin/deploy-cluster.sh
