apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: tat-tvam
  annotations:
    kubernetes.io/ingress.class: contour
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
  - secretName: tat-tvam-tls
    hosts:
    - tat-tvam.com
  rules:
  - host: tat-tvam.com
    http:
      paths:
      - backend:
          serviceName: service
          servicePort: 80
