apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: kannada-geetha
  annotations:
    kubernetes.io/ingress.class: contour
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
  - secretName: kannada-geetha-tls
    hosts:
    - kannadageetha.com
  rules:
  - host: kannadageetha.com
    http:
      paths:
      - backend:
          serviceName: service
          servicePort: 80
  - host: www.kannadageetha.com
    http:
      paths:
      - backend:
          serviceName: service
          servicePort: 80
